name: Generate 2000+ Players List

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # daily

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests --quiet

      - run: python -u script.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qualified-players
          path: qualified_players.txt
